### PR TITLE
fix: Fix cherry-picking on macOS

### LINKED ISSUE #18: Interactive cherry-pick tool fails on macOS
The data fed to the editor should look like:

```
60af9ad5 fix: Don't send drmsessionupdate after unload (#4248)
```

But on macOS, instead we get something like:

```
+ 60af9ad596e5c2cb31d1e7bb616e415cf46ca761 fix: Don't send drmsessionupdate after unload (#4248)
```

This is due to incompatibilities between GNU sed (on Linux, cygwin, etc) and BSD sed (on macOS).  The regex that trims the content before feeding it to the editor is failing.

### PR DESCRIPTION
**Pull request by joeyparrish**
This makes the interactive cherry-pick tool use a sed command that
works on both GNU sed (Linux) and BSD sed (macOS).

Closes #18

### CODE REVIEW

File: interactive-cherry-pick/interactive-cherry-pick.sh [hunk 1]
```diff
@@ -60,7 +60,9 @@ git cherry -v \
 
 # Remove the leading plus signs and trim the sha1s in the file to 8 characters,
 # to match what "git rebase -i" outputs.
-sed -i.backup -e 's/^+ \(\S\S\S\S\S\S\S\S\)\S*/\1/' "$cp_list"
+# NOTE: Take care to ensure that changes to this still work on macOS, which uses
+# BSD sed instead of GNU sed.
+sed -i.backup -re 's/^\+ ([a-fA-F0-9]{8})[a-fA-F0-9]*/\1/' "$cp_list"
```
Comment (theodab) [inline interactive-cherry-pick/interactive-cherry-pick.sh:65]: I made a dummy commit in my branch and tried this out. This is what I saw:

`+ 71b8324bfe0c098e3c2cb7d3bd4ba8028bbae5b3 feat(player): Dummy commit`

There was also an error in the terminal, saying `fatal: bad revision '+'`.
So it looks like this isn't working as intended.

Comment (joeyparrish) [reply interactive-cherry-pick/interactive-cherry-pick.sh:65]: Do you mean you tried that with the PR?  Or without?

Try this:

```sh
echo "+ 71b8324bfe0c098e3c2cb7d3bd4ba8028bbae5b3 feat(player): Dummy commit" \
  | sed -re 's/^\+ ([a-fA-F0-9]{8})[a-fA-F0-9]*/\1/'
```

Does it format the input correctly on your mac?

Comment (joeyparrish) [reply interactive-cherry-pick/interactive-cherry-pick.sh:65]: I double-checked, and this works on the mac in our lab.

Comment (theodab) [reply interactive-cherry-pick/interactive-cherry-pick.sh:65]: Oh... I checked again and I had forgotten to apply this PR before testing. Whoops!

**Review by theodab — APPROVED** [review]
